[build]
builder = "Dockerfile"

[deploy]
startCommand = "streamlit run app.py --server.port $PORT"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
