services:
  - type: web
    name: huddle-assistant
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: true
      - key: NOTION_API_KEY
        sync: true
      - key: NOTION_MEMORY_DB_ID
        sync: true
    autoDeploy: true
    buildFilter:
      paths:
        - Dockerfile
        - app.py
        - suggestor.py
        - memory_vector.py
        - memory_sync.py          # ✅ ADD THIS
        - doc_embedder.py         # ✅ OPTIONAL
        - notion_embedder.py      # ✅ OPTIONAL
        - requirements.txt
